//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadastroDeAlunos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cidades
    {
        public int id { get; set; }
        public string NomeCidade { get; set; }
        public string Estado { get; set; }
        public string Cep { get; set; }
    }
}
